### ISSUE TITLE
Package MARKUP does not exist

### ISSUE THREAD

**Issue by madam287** [MahdyMirzade/nyxt#2]
Just installed nyxt browser on manjaro and and wanted to try the Dracula theme. The following error appeared after copying the .lisp files and restarting nyxt. Apparently 'Package MARKUP does not exist'. Not sure where to go from here on..

```
Error occured:
Could not load the init file: READ error during LOAD:
Package MARKUP does not exist.
Line: 25, Column: -1, File-Position: 1894
Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/statusline.lisp" >{10071D1343}

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001170103}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {7F575B94677B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {10081B266B}> :PACKAGE :CL)
4: ((FLET "H0" :IN NYXT::LOAD-LISP) #<SB-C::INPUT-ERROR-IN-LOAD {10081B1873}>)
5: (SB-KERNEL::%SIGNAL #<SB-C::INPUT-ERROR-IN-LOAD {10081B1873}>)
6: (ERROR #<SB-C::INPUT-ERROR-IN-LOAD {10081B1873}>)
7: (SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {10081B17D3}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/statusline.lisp" {10071D1343}>)
8: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {10071D2C5B}> #<SB-C::SOURCE-INFO {10071D2C23}> SB-C::INPUT-ERROR-IN-LOAD)
9: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/statusline.lisp" {10071D1343}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
10: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/statusline.lisp" {10071D1343}> NIL)
11: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7F575B946ECB}> #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/statusline.lisp" {10071D1343}> NIL #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/statusline.lisp" {10071D1343}>)
12: (LOAD #P"/home/xxx/.config/nyxt/statusline.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
13: ((LAMBDA NIL :IN "/home/xxx/.config/nyxt/init.lisp"))
14: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DOLIST (NYXT:FILE (LIST (NYXT:NYXT-INIT-FILE "statusline.lisp") (NYXT:NYXT-INIT-FILE "stylesheet.lisp"))) (LOAD NYXT:FILE)) #<NULL-LEXENV>)
15: (SB-EXT:EVAL-TLF (DOLIST (NYXT:FILE (LIST (NYXT:NYXT-INIT-FILE "statusline.lisp") (NYXT:NYXT-INIT-FILE "stylesheet.lisp"))) (LOAD NYXT:FILE)) 1 NIL)
16: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (DOLIST (NYXT:FILE (LIST (NYXT:NYXT-INIT-FILE "statusline.lisp") (NYXT:NYXT-INIT-FILE "stylesheet.lisp"))) (LOAD NYXT:FILE)) 1)
17: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (DOLIST (NYXT:FILE (LIST (NYXT:NYXT-INIT-FILE "statusline.lisp") (NYXT:NYXT-INIT-FILE "stylesheet.lisp"))) (LOAD NYXT:FILE)) :CURRENT-INDEX 1)
18: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {10071166FB}> #<SB-C::SOURCE-INFO {10071166C3}> SB-C::INPUT-ERROR-IN-LOAD)
19: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/init.lisp" {10071150E3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
20: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/init.lisp" {10071150E3}> NIL)
21: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7F575B94787B}> #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/init.lisp" {10071150E3}> NIL #<SB-INT:FORM-TRACKING-STREAM for "file /home/xxx/.config/nyxt/init.lisp" {10071150E3}>)
22: (LOAD "/home/xxx/.config/nyxt/init.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
23: ((FLET NYXT::UNSAFE-LOAD :IN NYXT::LOAD-LISP))
24: (NYXT::LOAD-LISP "/home/xxx/.config/nyxt/init.lisp" :PACKAGE #<PACKAGE "NYXT-USER">)
25: (NYXT::START-BROWSER NIL)
26: (NYXT:START :URLS NIL)
27: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
28: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10066C9BBB}>)
29: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
30: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
31: (SB-IMPL::START-LISP)
```

**Comment by MahdiMirzadeh** [comment]
# Fixed
The current configuration (latest commit) should work now, I removed custom url changes because of the changes in the latest release _2.2.2_. If you want a cleaner interface, I suggest to compile _2.1.1_ which supported the options in the old config.
I'm not sure if Manjaro has the **nyxt** package inside its official repositories, I assume you installed it from [nyxt (AUR)](https://aur.archlinux.org/packages/nyxt).

# The issue
I need to point out that **nyxt** is still in developement, and there are some changes that will eventually occur during different releases and it'll effect configurations.
I need to also say this, In the current moment the latest version of **nyxt** has some loading problems. it crashes once you want to load a web buffer, this is due to the latest **WebKitGTK** update, If you also have this problem, you'll need to follow this issue in the official repository and wait until it's fixed: [nyxt#1840](https://github.com/atlas-engineer/nyxt/issues/1840)

If you can't wait until the next update in `master` branch, you can install [nyxt-browser-git (AUR)](https://aur.archlinux.org/packages/nyxt-browser-git), I just tested it and it loads fine and good, but it can also be a little buggy.

# Testing the update
Package: nyxt-browser-git 2.1.1.r469.gaf599d8d-1
System: Arch Linux

![image](https://user-images.githubusercontent.com/63877463/141039307-6364b532-1f18-4825-b2f9-c238772417a1.png)

Best Regards, Mahdy

**Comment by madam287** [comment]
Ok, so you commented out that part. I will not downgrade the Browser for the sake of theming. Thought you might know how to change it without the Markup package. I was just curious on that browser to play around a bit.

**Comment by MahdiMirzadeh** [comment]
The markup package, was included in the older versions of nyxtbrowser, it was how statuslines were written but they changed it, so I commented it, I also haven't looked into the new code so I could modify it further, because it's still in developement, what I said was that if you really wanted to test the old theme you may want to use the 2.1.1 or older. **However** the new update on this repo will work fine with the latest release and has no problems, you may just want to `git pull` and install it again.

But the latest official nyxtbrowser release has some issues in loading, I wanted to say it so you would try the nyxt-browser-git package and test it without any problems.

Best Regards, Mahdy
